//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MostraRotaWS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class coordenadas
    {
        public int id { get; set; }
        public string email_usr { get; set; }
        public int id_rota { get; set; }
        public float latitude { get; set; }
        public float longitude { get; set; }
        public System.DateTime datahora { get; set; }
    
        public virtual rotas rotas { get; set; }
    }
}
