//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MostraRotaWS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mostrarotaEntities : DbContext
    {
        public mostrarotaEntities()
            : base("name=mostrarotaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<coordenadas> coordenadas { get; set; }
        public virtual DbSet<rotas> rotas { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
    }
}
