//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MostraRotaWS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rotas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rotas()
        {
            this.coordenadas = new HashSet<coordenadas>();
        }
    
        public string email_usr { get; set; }
        public int id { get; set; }
        public System.DateTime dthr_ini { get; set; }
        public System.DateTime dthr_fim { get; set; }
        public int distancia { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<coordenadas> coordenadas { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
